export const EMAIL_CONSOLE_PREVIEW_ENV_FLAG =
  "BETTERAUTH_EMAIL_CONSOLE_PREVIEW";

export const EMAIL_BRAND_NAME_ENV_FLAG = "BETTERAUTH_EMAIL_BRAND_NAME";
export const EMAIL_BRAND_TAGLINE_ENV_FLAG =
  "BETTERAUTH_EMAIL_BRAND_TAGLINE";
export const EMAIL_BRAND_LOGO_URL_ENV_FLAG =
  "BETTERAUTH_EMAIL_BRAND_LOGO_URL";
